vim-jp-radio/LP

package.json, pnpm-lock.yaml, src/routes/Description.svelte, src/routes/Footer.svelte, src/routes/Personalities.svelte, src/routes/Platforms.svelte, src/routes/RadioLetter.svelte, svelte.config.js
- [BudouX](https://github.com/google/budoux/tree/main/javascript)を使って日本語の改行をいい感じにしていく（あなたとJAVA を回避できる）
- https://github.com/ryoppippi/svelte-preprocess-budoux/ を導入(ビルド時に分かち書きしてくれるのでruntime costはかからない)
導入前
導入後
=> BudouXを導入して改行をいい感じにしていく

plugins/generete-redirects.js
fixes: #180 
https://feature-180.lp-d1f.pages.dev/suzuri
=> feat(redirect): suzuri

uno.config.js
=> docs(unocss.config.js): 不要なcommentを削除

package.json, pnpm-lock.yaml, src/lib/Heading/Heading.svelte, uno.config.js
fixes: #175
https://github.com/vim-jp-radio/LP/assets/1560508/5d199754-f3f9-44c9-85db-b628c82f9149
=> feat(Heading.svelte): 見出しにアンカーをつける

src/routes/EasterEgg.svelte
特に ありすえ AA が 4kb ほどあったので、それを削減してみる
=> feat(EasterEgg): AA を 埋め込みでなくfetchにすることでbundle size 削減

src/lib/links/_links.ts, src/lib/links/index.ts, src/routes/+page.server.ts
=> feat(Tweet): リスナーの声のTweet IDを _links に移動

src/lib/Logo/_Base.svelte, src/routes/+error.svelte, src/routes/Footer.svelte, src/routes/Header.svelte, src/routes/Personality.svelte
img tag に loading=lazyを付与してfirst viewの速度を上げる
=> img tag に `loading='lazy'` を付与

package.json, pnpm-lock.yaml, src/lib/Logo/_Base.svelte, src/routes/+error.svelte, src/routes/Personality.svelte
一緒にupdateする必要があったので一つのPRでアップデート
Related: #234
=> chore(deps): update dependency svelte-eslint-parser to ^0.41.0 &  update dependency svelte to v5.0.0-next.208

package.json, pnpm-lock.yaml, vite.config.ts
update sveltweet
tweetの表示が崩れてなければok
=> chore(deps): update dependency sveltweet to  v0.2.3

package.json, pnpm-lock.yaml, src/lib/Heading/Heading.svelte, uno.config.ts, vite.config.ts
- extendThemeの使い方がやはり間違っていたので再度修正（だけどうまく表示されているのは妙)
- `colors` をnested objectで定義
=> feat(unocss): extendThemeの使い方を修正

package.json, pnpm-lock.yaml, src/routes/+page.server.ts
=> feat: tweet取得にretry処理を入れる

.npmrc
https://pnpm.io/ja/npmrc#manage-package-manager-versions
pnpmのversionをpnpmで管理するoption	
入れ忘れていたので
=> feat(pnpm):manage-package-manager-versions=true

uno.config.ts
v0.62.4で型がexportされるようになったのでそれを用いている
https://github.com/unocss/unocss/commit/c315fa9f#diff-8e461196f9fdcaa9968f2e8cf76661b0e80dc5a97d33b3d381a7a192204868adL2
=> feat(unocss): カスタマイズしたthemeに型情報を追加

package.json
only-allowでpnpmのみを許可する
それ以外はエラーが出る
=> feat(package.json): only allow pnpm

package.json, pnpm-lock.yaml, svelte.config.js
最新のsvelteと相性が良くないらしく、一旦 sveltekit-html-minifierを外します
実際、svelteの最新版でエラーが発生しているので、一旦のぞきます
https://github.com/sveltejs/svelte/issues/13510
=> chore: remove html-minifier

package.json, pnpm-lock.yaml, vite.config.ts
vite-plugin-faviconsをアプデし、cacheをonにしました
ビルドが手元では早くなる
=> chore: update vite-plugin-favicons

package.json, pnpm-lock.yaml, src/routes/Meta.svelte
- いらない依存のfaviconsを削除
- comment outされてた記述を削除
=> favicons関係のいらない記述を削除

uno.config.ts, vite.config.ts
not important fix because they are in comments :)
=> chore: fix typo in comments

.githooks/pre-commit, .githooks/pre-push, .husky/pre-commit, .husky/pre-push, package.json, pnpm-lock.yaml
=> pre-commitにhusky/lint-stagedを使う

src/lib/Backgroud/Backgroud.svelte
https://svelte.dev/docs/svelte/svelte-reactivity-window
advent of svelteで追加されたruneを使用
fixes: #339
=> svlete innerWidth innerHeightを使う

svelte.config.js
使っているライブラリすべてsvelte5対応したので設定を削除
=> chore: remove vite config
